services:
  caddy:
    image: caddy
    container_name: caddy_server
    restart: unless-stopped
    volumes:
      - ${CADDYFILE_PATH}:/etc/caddy/Caddyfile
      - ${CADDY_DATA_PATH}:/data
      - ${CADDY_CONFIG_PATH}:/config
      - ${CERT_PATH}:/etc/ssl/cert.pem
      - ${KEY_PATH}:/etc/ssl/server.key
    ports:
      - "443:443"
    networks:
      - internal_network

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    container_name: middleware
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - type: bind
        source: ./middleware/endpoints.yaml
        target: /workspace/endpoints.yaml
        consistency: consistent
      - type: bind
        source: ./middleware/secrets.yaml
        target: /workspace/secrets.yaml
        consistency: consistent
    networks:
      - internal_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment:
      - PORT=3000
      - DEFAULT_USER_ROLE=pending
      - ENABLE_ADMIN_CHAT_ACCESS=False
      - ENABLE_COMMUNITY_SHARING=False
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ENABLE_OLLAMA_API=False
      - WEBUI_NAME=${WEBUI_NAME}
      - OPENAI_API_BASE_URLS=http://middleware:9000/v1
      - OPENAI_API_KEYS=${OPENWEBUI_GROUP_KEY}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OPENID_PROVIDER_URL=${OPENID_PROVIDER_URL}
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME}
      - ENABLE_OAUTH_SIGNUP=True
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=True
    volumes:
      - ./openwebui/data:/app/backend/data
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
